### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by martchellop** [martchellop/Entretenibit#122]
Docker-compose needs to run as if we have started the 3 parts separability. Which means it has to have all the pages in the frontend and there needs to be a network working properly to make the front and backend talk to each other.

**Comment by LTKills** [comment]
I'm sorry it took me so long to take a look here. This doesn't seem to be a bug (at least I can't reproduce it on my computer).

@BrunoGomesCoelho @martchellop @matheushjs  could you try this on your PCs and tell me if there are any errors? Remember to pull the master branch and use `docker-compose up` on the app's root directory.

**Comment by matheushjs** [comment]
On out last meeting, 2 bugs were reported:

1. The "About Us" page wasn't showing

2. The frontend wasn't communicating correctly with the server

The last one was actually a **possible** bug that @martchellop got pissed off about because I didn't test the communication after accepting the docker-compose pull request.

Anyway, I'm not experiencing neither of the bugs. I can access the "About Us" and the frontend is retrieving data from the server correctly too.
