### ISSUE TITLE
Populate the DB

### ISSUE THREAD

**Issue by martchellop** [martchellop/Entretenibit#90]
We need more events in the data base to test our project, so we need to scrape more different pages.

**Comment by BrunoGomesCoelho** [comment]
Blocked by #111 for now.
Also, since I have the chance, could you have a look at this [file](https://github.com/martchellop/Entretenibit/blob/populate-DB/robot/scrapers/UFSCarEventsScraper.py) @matheushjs  ? 
Since you started the web scrape and did such a good job, I would like to know if there's anything you would suggesting changing before going on and doing more events.

**Comment by matheushjs** [comment]
Didn't test it locally, but I've read it thoroughly and seems perfect to me.
Of course, this does not mean it is in fact perfect, as I'm not even near being slightly skillful in Python programming, web scraping and such.
But yeah, from my point of view that brims with partiality, the said file looks really well written.
